# Generated by Django 6.0.6 on 2026-07-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0002_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='payment_status',
        ),
    ]
