# Generated by Django 6.0.6 on 2026-07-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0003_remove_admission_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='remarks',
            new_name='message',
        ),
    ]
