# Generated by Django 6.0.6 on 2026-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0004_rename_remarks_admission_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='course',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='preferred_center',
        ),
        migrations.AddField(
            model_name='admission',
            name='career_track',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='selected_center',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
