# Generated by Django 6.0.6 on 2026-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0005_remove_admission_course_remove_admission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='selected_center',
            field=models.CharField(default='South Bengaluru (Head Office)', max_length=255),
        ),
    ]
