
# Generated by Django 6.0.6 on 2026-07-04 14:24

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='track',
            field=models.CharField(
                choices=[
                    ('general', 'General'),
                    ('white-collar', 'White Collar'),
                    ('blue-collar', 'Blue Collar'),
                ],
                max_length=50,
            ),
        ),
    ]