# Generated by Django 6.0.6 on 2026-07-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0008_admission_created_at_alter_contact_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
