# Generated by Django 6.0.6 on 2026-07-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabapp', '0010_callbackrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('division', models.CharField(choices=[('Modeling Foundation', 'Modeling Foundation'), ('Ramp Modeling', 'Ramp Modeling'), ('Print Modeling', 'Print Modeling'), ('Commercial Modeling', 'Commercial Modeling'), ('E-Commerce Modeling', 'E-Commerce Modeling'), ('Catalogue Modeling', 'Catalogue Modeling'), ('Bridal Modeling', 'Bridal Modeling'), ('Ethnic Wear Modeling', 'Ethnic Wear Modeling'), ('Luxury Modeling', 'Luxury Modeling')], max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
